### ISSUE TITLE
README sample code is broken (upstream also)

### ISSUE THREAD

**Issue by grempe** [hirusi/eleventy-plugin-safe-external-links#2]
The setup instructions in the README are broken (and they are broken in the upstream repo as well).

* Incorrect `const` assignment, copy/paste error from another plugin, invalid plugin (not `@hirusi/...`
* Incorrect plugin config, extra closing brace, incorrect plugin const name

Should be:

```js
const safeExternalLinks = require("@hirusi/eleventy-plugin-safe-external-links")

module.exports = function (eleventyConfig) {
  ...snip...

  eleventyConfig.addPlugin(safeExternalLinks, {
    pattern: "https{0,1}://", // RegExp pattern for external links
    noopener: true, // Whether to include noopener
    noreferrer: false, // Whether to include noreferrer
    files: [
      // What output file extensions to work on
      ".html",
    ],
  })

  ...snip...
}
```

Most of these issues also apply to the README in the upstream repo where these issues seem to have originated:

https://github.com/chromeos/static-site-scaffold-modules/blob/master/modules/eleventy-plugin-safe-external-links/README.md

**Comment by hirusi** [comment]
Hi @grempe! 😊

Thank you for pointing this out! Would you like to open a PR or are you happy for me to fix this?

Personally I hand-wrote my config as follows, and didn't think to test this from the README:

```
        config.addPlugin(require("@hirusi/eleventy-plugin-safe-external-links"), {
		pattern: "https{0,1}://", // RegExp pattern for external links
		noopener: true, // Whether to include noopener
		noreferrer: true, // Whether to include noreferrer
		files: [
			// What output file extensions to work on
			".html"
		]
	});
```

**Comment by grempe** [comment]
Happy to have you resolve.

I think my use of require is more idiomatic.

I'm not sure if setting both values to true as the default is necessary.

https://pointjupiter.com/what-noopener-noreferrer-nofollow-explained/

Cheers

**Comment by hirusi** [comment]
...and we're good - thanks @grempe!
